CREATE TABLE COMPANY(
    company_id INT AUTO_INCREMENT NOT NULL,
    name VARCHAR(255) NOT NULL,
    sector VARCHAR(255) NOT NULL,
    market_cap BIGINT NOT NULL,
    ebitda VARCHAR(255) NOT NULL,
    revenue_growth decimal(8,4) NOT NULL,
    PRIMARY KEY (company_id)
);

CREATE TABLE USERS (
    id INT AUTO_INCREMENT NOT NULL,
    email VARCHAR(255) NOT NULL,
    username VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE (email)
);

CREATE TABLE INVESTORS (
    investor_id INT NOT NULL AUTO_INCREMENT,
	id INT NOT NULL, 
    PRIMARY KEY (investor_id),
    FOREIGN KEY (id) REFERENCES USERS(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Private_Company_CEO (
    ceo_id INT NOT NULL AUTO_INCREMENT,  
    id INT NOT NULL,       
    company_id INT NOT NULL,    
    starting_date TIMESTAMP NOT NULL,
    PRIMARY KEY (ceo_id),       
    FOREIGN KEY (id) REFERENCES USERS(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (company_id) REFERENCES COMPANY(company_id)
);


CREATE TABLE SHORTLIST (
	sid INT AUTO_INCREMENT NOT NULL, 
	sname varchar(30) NOT NULL, 
	user_id INT NOT NULL,
    PRIMARY KEY (sid),
    FOREIGN KEY (user_id) REFERENCES USERS(id) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE SHORTLIST_CONTAINS (
	sid INT NOT NULL, 
	company_id INT NOT NULL, 
	user_id INT NOT NULL, 
	date_shortlisted TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (sid, company_id),
	FOREIGN KEY (sid) REFERENCES shortlist(sid) ON DELETE CASCADE ON UPDATE CASCADE, 
	FOREIGN KEY (company_id) REFERENCES COMPANY(company_id)
);