CREATE DATABASE testDB;
USE testDB;
CREATE TABLE student(uid DECIMAL(3, 0) NOT NULL PRIMARY KEY, name VARCHAR(30), score DECIMAL(3, 2));
INSERT INTO student VALUES(1, ’alice’, 0.1);
INSERT INTO student VALUES(2, ’bob’, 0.4);
SELECT * FROM student;